version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: pantry-mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: pantrydb
      MYSQL_USER: app
      MYSQL_PASSWORD: senha123
    volumes:
      - /home/rodrigo/labs/lab-java/db/mysql/data/:/var/lib/mysql
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
